import { z } from 'zod'

export const wsClientEvents = {
  PRESENCE_PING: 'presence.ping',
  QUEUE_SUBSCRIBE: 'queue.subscribe',
  MATCH_SUBSCRIBE: 'match.subscribe',
  MATCH_READY: 'match.ready',
  MATCH_RESYNC: 'match.resync',
  ROOM_SUBSCRIBE: 'room.subscribe',
  ROOM_RESYNC: 'room.resync',
  TOURNAMENT_SUBSCRIBE: 'tournament.subscribe',
  TOURNAMENT_RESYNC: 'tournament.resync',
  FRIENDS_SUBSCRIBE: 'friends.subscribe',
  SPECTATOR_SUBSCRIBE: 'spectator.subscribe',
  SPECTATOR_RESYNC: 'spectator.resync',
  EDITOR_UPDATE: 'editor.update',
} as const

export const wsServerEvents = {
  QUEUE_JOINED: 'queue.joined',
  QUEUE_SEARCHING: 'queue.searching',
  MATCH_FOUND: 'match.found',
  MATCH_STARTING: 'match.starting',
  MATCH_ACTIVE: 'match.active',
  MATCH_PARTICIPANT_UPDATE: 'match.participant_update',
  SUBMISSION_QUEUED: 'submission.queued',
  SUBMISSION_PROGRESS: 'submission.progress',
  SUBMISSION_RESULT: 'submission.result',
  MATCH_EVALUATING: 'match.evaluating',
  MATCH_RESOLVED: 'match.resolved',
  MATCH_SNAPSHOT: 'match.snapshot',
  OBSERVER_SNAPSHOT: 'observer.snapshot',
  ADMIN_JOINED: 'admin.joined',
  ADMIN_LEFT: 'admin.left',
  MATCH_ADJUDICATED: 'match.adjudicated',
  RATING_UPDATED: 'rating.updated',
  ROOM_CREATED: 'room.created',
  ROOM_UPDATED: 'room.updated',
  ROOM_JOINED: 'room.joined',
  ROOM_LEFT: 'room.left',
  ROOM_READY: 'room.ready',
  ROOM_UNREADY: 'room.unready',
  ROOM_LOCKED: 'room.locked',
  ROOM_STARTED: 'room.started',
  ROOM_MATCH_CREATED: 'room.match_created',
  ROOM_FINISHED: 'room.finished',
  ROOM_CANCELLED: 'room.cancelled',
  ROOM_SNAPSHOT: 'room.snapshot',
  TOURNAMENT_CREATED: 'tournament.created',
  TOURNAMENT_UPDATED: 'tournament.updated',
  TOURNAMENT_REGISTRATION_OPENED: 'tournament.registration_opened',
  TOURNAMENT_REGISTRATION_CLOSED: 'tournament.registration_closed',
  TOURNAMENT_STARTED: 'tournament.started',
  TOURNAMENT_MATCH_CREATED: 'tournament.match_created',
  TOURNAMENT_MATCH_STARTED: 'tournament.match_started',
  TOURNAMENT_MATCH_COMPLETED: 'tournament.match_completed',
  TOURNAMENT_ROUND_COMPLETED: 'tournament.round_completed',
  TOURNAMENT_PLAYER_ELIMINATED: 'tournament.player_eliminated',
  TOURNAMENT_FINAL_STARTED: 'tournament.final_started',
  TOURNAMENT_COMPLETED: 'tournament.completed',
  TOURNAMENT_SNAPSHOT: 'tournament.snapshot',
  // Social / presence events
  PRESENCE_UPDATED: 'presence.updated',
  FRIEND_REQUEST: 'friend.request',
  FRIEND_ACCEPTED: 'friend.accepted',
  FRIEND_REMOVED: 'friend.removed',
  CHALLENGE_RECEIVED: 'challenge.received',
  CHALLENGE_ACCEPTED: 'challenge.accepted',
  CHALLENGE_DECLINED: 'challenge.declined',
  CHALLENGE_EXPIRED: 'challenge.expired',
  CHALLENGE_CANCELLED: 'challenge.cancelled',
  CHALLENGE_MATCH_CREATED: 'challenge.match_created',
  // Spectator / live code events
  SPECTATOR_SNAPSHOT: 'spectator.snapshot',
  SPECTATOR_JOINED: 'spectator.joined',
  SPECTATOR_LEFT: 'spectator.left',
  SPECTATOR_COUNT: 'spectator.count',
  EDITOR_SNAPSHOT: 'editor.snapshot',
  EDITOR_UPDATE_BROADCAST: 'editor.update_broadcast',
  ERROR: 'error',
} as const

export const wsEnvelopeSchema = z.object({
  type: z.string(),
  id: z.string().optional(),
  ts: z.string().optional(),
  matchId: z.string().uuid().optional(),
  payload: z.unknown().optional(),
})

export type WsEnvelope = z.infer<typeof wsEnvelopeSchema>
