export class AppError extends Error {
  constructor(
    public readonly code: string,
    message: string,
    public readonly statusCode = 400,
    public readonly retryable = false,
  ) {
    super(message)
    this.name = 'AppError'
  }
}

export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION: 'VALIDATION',
  RATE_LIMITED: 'RATE_LIMITED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  ALREADY_IN_QUEUE: 'ALREADY_IN_QUEUE',
  NOT_IN_QUEUE: 'NOT_IN_QUEUE',
  ALREADY_IN_MATCH: 'ALREADY_IN_MATCH',
  MATCH_NOT_ACTIVE: 'MATCH_NOT_ACTIVE',
  IDEMPOTENCY_REPLAY: 'IDEMPOTENCY_REPLAY',
  INTERNAL: 'INTERNAL',
  ALREADY_FRIENDS: 'ALREADY_FRIENDS',
  FRIEND_REQUEST_PENDING: 'FRIEND_REQUEST_PENDING',
  NOT_FRIENDS: 'NOT_FRIENDS',
  SELF_ACTION: 'SELF_ACTION',
  CHALLENGE_EXPIRED: 'CHALLENGE_EXPIRED',
  CHALLENGE_INVALID: 'CHALLENGE_INVALID',
  CHALLENGE_CONFLICT: 'CHALLENGE_CONFLICT',
} as const
