/**
 * Hard difficulty questions — DP, advanced graphs, greedy, segment tree, backtracking.
 */
export const hardQuestions = [
  {
    slug: 'grid-paths-obstacles',
    title: 'Grid Paths With Obstacles',
    topic: 'algorithms',
    tags: ['dp', '2d', 'grid'],
    difficultyId: 'hard' as const,
    promptMd: '# Grid Paths With Obstacles\n\nYou are given an r x c grid. Some cells are blocked (marked 1), others are open (marked 0). You start at the top-left cell (0, 0) and want to reach the bottom-right cell (r-1, c-1). You can only move right or down.\n\nPrint the number of distinct paths from start to finish, modulo 1000000007. If the start or end cell is blocked, the answer is 0.\n\n## Input Format\n- First line: two integers r and c (1 ≤ r, c ≤ 1000)\n- Next r lines: each contains c integers (0 or 1)\n\n## Output Format\n- Print one integer: the number of paths mod 1000000007',
    examples: [
      {
        input: '3 3\n0 0 0\n0 1 0\n0 0 0',
        output: '2',
        explanation: 'The two paths go around the blocked center cell.',
      },
    ],
    testCases: [
      { visibility: 'public' as const, input: '3 3\n0 0 0\n0 1 0\n0 0 0', expectedOutput: '2', weight: 1 },
      { visibility: 'public' as const, input: '1 1\n0', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '2 2\n1 0\n0 0', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: '1 5\n0 0 0 0 0', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '5 1\n0\n0\n0\n0\n0', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '4 4\n0 1 0 0\n0 0 1 0\n1 0 0 0\n0 0 0 0', expectedOutput: '3', weight: 2 },
      { visibility: 'hidden' as const, input: '3 3\n0 0 0\n0 0 0\n1 1 1', expectedOutput: '0', weight: 2 },
    ],
  },
  {
    slug: 'bounded-knapsack',
    title: 'Bounded Knapsack',
    topic: 'algorithms',
    tags: ['dp', 'knapsack'],
    difficultyId: 'hard' as const,
    promptMd: '# Bounded Knapsack\n\nYou have n items and a knapsack with capacity W. Item i has weight w[i] and value v[i]. You may take at most c[i] copies of item i. Print the maximum total value achievable.\n\n## Input Format\n- First line: two integers n and W (1 ≤ n ≤ 100, 1 ≤ W ≤ 10000)\n- Next n lines: three integers w[i], v[i], c[i] (1 ≤ w[i] ≤ 100, 1 ≤ v[i] ≤ 100, 1 ≤ c[i] ≤ 100)\n\n## Output Format\n- Print one integer: the maximum value',
    examples: [
      {
        input: '3 10\n2 6 2\n3 8 1\n5 12 2',
        output: '26',
        explanation: 'Take 2 of item 1 (value 12), 1 of item 2 (value 8), and 1 of item 3 (value 12). Total 32 is over capacity. Optimal: 1 of item 2 (3 wt, 8 val) + 2 of item 3 (10 wt, 24 val) exceeds capacity. Best: 2 of item 1 + 1 of item 3 = 4+5=9 wt, 12+12=24 val. Actually 2 of item 1 (4wt,12val) + 1 of item 2 (3wt,8val) + 1 of item 3 (5wt,12val) = 12wt > 10. Try 1 of item 2 + 1 of item 3 = 8wt, 20val, then 1 more of item 1 = 10wt, 26val.',
      },
    ],
    testCases: [
      { visibility: 'public' as const, input: '3 10\n2 6 2\n3 8 1\n5 12 2', expectedOutput: '26', weight: 1 },
      { visibility: 'public' as const, input: '1 5\n3 10 1', expectedOutput: '10', weight: 1 },
      { visibility: 'hidden' as const, input: '1 5\n6 10 1', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: '2 10\n5 10 2\n5 10 2', expectedOutput: '20', weight: 2 },
      { visibility: 'hidden' as const, input: '3 6\n3 5 1\n2 3 3\n1 1 10', expectedOutput: '9', weight: 2 },
      { visibility: 'hidden' as const, input: '1 10000\n1 1 100', expectedOutput: '100', weight: 2 },
    ],
  },
  {
    slug: 'dijkstra-shortest-path',
    title: 'Dijkstra Shortest Path',
    topic: 'algorithms',
    tags: ['graph', 'shortest-path', 'dijkstra'],
    difficultyId: 'hard' as const,
    promptMd: '# Dijkstra Shortest Path\n\nYou are given a weighted directed graph with n vertices (labeled 1 to n) and m edges. All edge weights are non-negative. Print the shortest distance from vertex 1 to vertex n. If vertex n is unreachable, print -1.\n\n## Input Format\n- First line: two integers n and m (2 ≤ n ≤ 100000, 1 ≤ m ≤ 200000)\n- Next m lines: three integers u, v, w (1 ≤ u, v ≤ n, 0 ≤ w ≤ 1000000)\n\n## Output Format\n- Print one integer: the shortest distance or -1',
    examples: [
      {
        input: '4 4\n1 2 1\n2 3 2\n1 3 5\n3 4 1',
        output: '4',
        explanation: 'Path 1->2->3->4 has total weight 1+2+1 = 4.',
      },
    ],
    testCases: [
      { visibility: 'public' as const, input: '4 4\n1 2 1\n2 3 2\n1 3 5\n3 4 1', expectedOutput: '4', weight: 1 },
      { visibility: 'public' as const, input: '2 0', expectedOutput: '-1', weight: 1 },
      { visibility: 'hidden' as const, input: '2 1\n1 2 5', expectedOutput: '5', weight: 1 },
      { visibility: 'hidden' as const, input: '2 1\n2 1 5', expectedOutput: '-1', weight: 2 },
      { visibility: 'hidden' as const, input: '3 3\n1 2 10\n2 3 10\n1 3 100', expectedOutput: '20', weight: 2 },
      { visibility: 'hidden' as const, input: '5 4\n1 2 1\n2 3 1\n3 4 1\n4 5 1', expectedOutput: '4', weight: 2 },
    ],
  },
  {
    slug: 'detect-cycle-directed',
    title: 'Detect Cycle In Directed Graph',
    topic: 'algorithms',
    tags: ['graph', 'cycle-detection', 'dfs'],
    difficultyId: 'hard' as const,
    promptMd: '# Detect Cycle In Directed Graph\n\nYou are given a directed graph with n vertices and m edges. Print `yes` if the graph contains at least one cycle, otherwise `no`.\n\n## Input Format\n- First line: two integers n and m (1 ≤ n ≤ 100000, 0 ≤ m ≤ 200000)\n- Next m lines: two integers u and v (1 ≤ u, v ≤ n), meaning a directed edge from u to v\n\n## Output Format\n- Print `yes` or `no`',
    examples: [
      {
        input: '4 4\n1 2\n2 3\n3 1\n3 4',
        output: 'yes',
        explanation: 'Vertices 1, 2, 3 form a cycle.',
      },
    ],
    testCases: [
      { visibility: 'public' as const, input: '4 4\n1 2\n2 3\n3 1\n3 4', expectedOutput: 'yes', weight: 1 },
      { visibility: 'public' as const, input: '3 2\n1 2\n2 3', expectedOutput: 'no', weight: 1 },
      { visibility: 'hidden' as const, input: '1 1\n1 1', expectedOutput: 'yes', weight: 1 },
      { visibility: 'hidden' as const, input: '1 0', expectedOutput: 'no', weight: 1 },
      { visibility: 'hidden' as const, input: '5 5\n1 2\n2 3\n3 4\n4 5\n5 2', expectedOutput: 'yes', weight: 2 },
      { visibility: 'hidden' as const, input: '4 3\n1 2\n3 4\n1 3', expectedOutput: 'no', weight: 2 },
    ],
  },
  {
    slug: 'activity-selection-weighted',
    title: 'Weighted Activity Selection',
    topic: 'algorithms',
    tags: ['greedy', 'dp', 'interval'],
    difficultyId: 'hard' as const,
    promptMd: '# Weighted Activity Selection\n\nYou are given n activities. Activity i starts at time s[i], ends at time f[i], and has weight w[i]. You may select any subset of non-overlapping activities to maximize total weight. Two activities overlap if one starts before the other ends (intervals [s, f) are half-open).\n\nPrint the maximum total weight.\n\n## Input Format\n- First line: integer n (1 ≤ n ≤ 1000)\n- Next n lines: three integers s[i], f[i], w[i] (0 ≤ s[i] < f[i] ≤ 100000, 1 ≤ w[i] ≤ 10000)\n\n## Output Format\n- Print one integer: the maximum weight',
    examples: [
      {
        input: '4\n1 3 5\n2 5 6\n4 7 8\n6 9 3',
        output: '13',
        explanation: 'Select activities 1 (1-3, w=5) and 3 (4-7, w=8). Total = 13.',
      },
    ],
    testCases: [
      { visibility: 'public' as const, input: '3\n1 3 5\n2 5 6\n4 7 8', expectedOutput: '13', weight: 1 },
      { visibility: 'public' as const, input: '1\n1 5 10', expectedOutput: '10', weight: 1 },
      { visibility: 'hidden' as const, input: '3\n1 2 3\n2 3 4\n3 4 5', expectedOutput: '12', weight: 1 },
      { visibility: 'hidden' as const, input: '4\n1 5 10\n2 3 5\n3 6 8\n6 9 7', expectedOutput: '20', weight: 2 },
      { visibility: 'hidden' as const, input: '5\n1 3 2\n3 5 3\n5 7 4\n7 9 5\n2 8 10', expectedOutput: '14', weight: 2 },
    ],
  },
  {
    slug: 'longest-common-subsequence',
    title: 'Longest Common Subsequence',
    topic: 'algorithms',
    tags: ['dp', 'strings', 'lcs'],
    difficultyId: 'hard' as const,
    promptMd: '# Longest Common Subsequence\n\nGiven two strings s1 and s2, find the length of their longest common subsequence (not necessarily contiguous). Print that length.\n\n## Input Format\n- First line: string s1 (1 ≤ |s1| ≤ 1000)\n- Second line: string s2 (1 ≤ |s2| ≤ 1000)\n\nBoth strings contain only lowercase English letters.\n\n## Output Format\n- Print one integer: the LCS length',
    examples: [
      {
        input: 'abcde\nace',
        output: '3',
        explanation: '"ace" is a subsequence of both strings.',
      },
    ],
    testCases: [
      { visibility: 'public' as const, input: 'abcde\nace', expectedOutput: '3', weight: 1 },
      { visibility: 'public' as const, input: 'abc\nabc', expectedOutput: '3', weight: 1 },
      { visibility: 'hidden' as const, input: 'abc\ndef', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: 'a\na', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: 'abcba\nabcbabc', expectedOutput: '5', weight: 2 },
      { visibility: 'hidden' as const, input: 'aaaaaaaaa\naaaa', expectedOutput: '4', weight: 2 },
    ],
  },
  {
    slug: 'count-inversions',
    title: 'Count Inversions',
    topic: 'algorithms',
    tags: ['divide-conquer', 'merge-sort', 'arrays'],
    difficultyId: 'hard' as const,
    promptMd: '# Count Inversions\n\nAn inversion in an array is a pair (i, j) where i < j and a[i] > a[j]. Given an array of n integers, print the total number of inversions.\n\n## Input Format\n- First line: integer n (1 ≤ n ≤ 100000)\n- Second line: n integers a[1], ..., a[n] (1 ≤ a[i] ≤ 1000000000)\n\n## Output Format\n- Print one integer: the inversion count',
    examples: [
      {
        input: '5\n2 4 1 3 5',
        output: '3',
        explanation: 'Inversions: (2,1), (4,1), (4,3).',
      },
    ],
    testCases: [
      { visibility: 'public' as const, input: '5\n2 4 1 3 5', expectedOutput: '3', weight: 1 },
      { visibility: 'public' as const, input: '3\n1 2 3', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: '3\n3 2 1', expectedOutput: '3', weight: 1 },
      { visibility: 'hidden' as const, input: '1\n5', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: '6\n5 4 2 1 3 6', expectedOutput: '8', weight: 2 },
      { visibility: 'hidden' as const, input: '4\n1 1 1 1', expectedOutput: '0', weight: 2 },
    ],
  },
  {
    slug: 'edit-distance',
    title: 'Edit Distance',
    topic: 'algorithms',
    tags: ['dp', 'strings', 'edit-distance'],
    difficultyId: 'hard' as const,
    promptMd: '# Edit Distance\n\nGiven two strings s and t, compute the minimum number of single-character edits (insertions, deletions, substitutions) required to transform s into t.\n\n## Input Format\n- First line: string s (0 ≤ |s| ≤ 1000)\n- Second line: string t (0 ≤ |t| ≤ 1000)\n\nBoth strings contain only lowercase English letters.\n\n## Output Format\n- Print one integer: the edit distance',
    examples: [
      {
        input: 'horse\nros',
        output: '3',
        explanation: 'horse -> rorse (substitute h->r) -> rose (delete r) -> ros (delete e).',
      },
    ],
    testCases: [
      { visibility: 'public' as const, input: 'horse\nros', expectedOutput: '3', weight: 1 },
      { visibility: 'public' as const, input: 'abc\nabc', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: 'abc\n', expectedOutput: '3', weight: 1 },
      { visibility: 'hidden' as const, input: '\nabc', expectedOutput: '3', weight: 1 },
      { visibility: 'hidden' as const, input: 'saturday\nsunday', expectedOutput: '3', weight: 2 },
      { visibility: 'hidden' as const, input: 'a\nb', expectedOutput: '1', weight: 2 },
    ],
  },
  {
    slug: 'n-queens-count',
    title: 'N-Queens Count',
    topic: 'algorithms',
    tags: ['backtracking', 'recursion'],
    difficultyId: 'hard' as const,
    promptMd: '# N-Queens Count\n\nPlace n queens on an n x n chessboard such that no two queens attack each other (no two share the same row, column, or diagonal). Print the total number of distinct valid configurations.\n\n## Input Format\n- One integer n (1 ≤ n ≤ 14)\n\n## Output Format\n- Print one integer: the number of valid configurations',
    examples: [
      {
        input: '4',
        output: '2',
        explanation: 'There are 2 distinct solutions for 4 queens.',
      },
    ],
    testCases: [
      { visibility: 'public' as const, input: '4', expectedOutput: '2', weight: 1 },
      { visibility: 'public' as const, input: '1', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '2', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: '3', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: '8', expectedOutput: '92', weight: 2 },
      { visibility: 'hidden' as const, input: '10', expectedOutput: '724', weight: 2 },
      { visibility: 'hidden' as const, input: '12', expectedOutput: '14200', weight: 3 },
    ],
  },
  {
    slug: 'robot-simulation',
    title: 'Robot Simulation',
    topic: 'algorithms',
    tags: ['simulation', 'grid'],
    difficultyId: 'hard' as const,
    promptMd: '# Robot Simulation\n\nA robot starts at position (0, 0) facing north on an infinite grid. You receive a sequence of commands:\n- `G`: move forward 1 unit in current direction\n- `L`: turn left 90 degrees\n- `R`: turn right 90 degrees\n\nAfter executing all commands once, the robot repeats the entire sequence k times total. Print the squared Euclidean distance from origin to final position (this is always an integer).\n\n## Input Format\n- First line: string of commands (1 ≤ length ≤ 100)\n- Second line: integer k (1 ≤ k ≤ 1000000000)\n\n## Output Format\n- Print one integer: squared distance from (0,0)',
    examples: [
      {
        input: 'GGLLGG\n2',
        output: '0',
        explanation: 'After one cycle the robot returns to origin facing south. After 2 cycles it is still at origin.',
      },
    ],
    testCases: [
      { visibility: 'public' as const, input: 'GGLLGG\n2', expectedOutput: '0', weight: 1 },
      { visibility: 'public' as const, input: 'GG\n5', expectedOutput: '100', weight: 1 },
      { visibility: 'hidden' as const, input: 'L\n4', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: 'GGGR\n2', expectedOutput: '18', weight: 2 },
      { visibility: 'hidden' as const, input: 'G\n1000000000', expectedOutput: '1000000000000000000', weight: 3 },
      { visibility: 'hidden' as const, input: 'RGLRG\n1000000000', expectedOutput: '0', weight: 3 },
    ],
  },
  {
    slug: 'segment-tree-range-sum',
    title: 'Segment Tree Range Sum',
    topic: 'data-structures',
    tags: ['segment-tree', 'range-query', 'update'],
    difficultyId: 'hard' as const,
    promptMd: '# Segment Tree Range Sum\n\nYou are given an array of n integers. Process q queries of two types:\n- `1 i v`: set a[i] = v (1-indexed)\n- `2 l r`: print the sum of elements from index l to r (inclusive, 1-indexed)\n\n## Input Format\n- First line: two integers n and q (1 ≤ n ≤ 100000, 1 ≤ q ≤ 100000)\n- Second line: n integers a[1], ..., a[n] (0 ≤ a[i] ≤ 1000)\n- Next q lines: each query in the format described above\n\n## Output Format\n- For each type-2 query, print the sum on its own line',
    examples: [
      {
        input: '5 4\n1 2 3 4 5\n2 1 5\n1 3 10\n2 2 4\n2 1 5',
        output: '15\n16\n22',
        explanation: 'Sum 1..5 = 15. After setting a[3]=10: sum 2..4 = 2+10+4 = 16, sum 1..5 = 1+2+10+4+5 = 22.',
      },
    ],
    testCases: [
      { visibility: 'public' as const, input: '5 4\n1 2 3 4 5\n2 1 5\n1 3 10\n2 2 4\n2 1 5', expectedOutput: '15\n16\n22', weight: 1 },
      { visibility: 'public' as const, input: '1 1\n42\n2 1 1', expectedOutput: '42', weight: 1 },
      { visibility: 'hidden' as const, input: '3 3\n1 2 3\n2 1 1\n2 2 2\n2 3 3', expectedOutput: '1\n2\n3', weight: 1 },
      { visibility: 'hidden' as const, input: '4 3\n0 0 0 0\n1 2 5\n2 1 4\n2 2 2', expectedOutput: '5\n5', weight: 2 },
      { visibility: 'hidden' as const, input: '5 5\n10 20 30 40 50\n2 1 5\n1 3 0\n2 1 5\n1 1 100\n2 1 5', expectedOutput: '150\n120\n210', weight: 2 },
    ],
  },
  {
    slug: 'word-break',
    title: 'Word Break',
    topic: 'algorithms',
    tags: ['dp', 'strings', 'trie'],
    difficultyId: 'hard' as const,
    promptMd: '# Word Break\n\nGiven a string s and a dictionary of words, determine if s can be segmented into a space-separated sequence of dictionary words. Print `yes` if possible, `no` otherwise.\n\n## Input Format\n- First line: string s (1 ≤ |s| ≤ 1000)\n- Second line: integer n (number of dictionary words, 1 ≤ n ≤ 1000)\n- Next n lines: one dictionary word each (1 ≤ |word| ≤ 100)\n\nAll strings contain only lowercase English letters.\n\n## Output Format\n- Print `yes` or `no`',
    examples: [
      {
        input: 'leetcode\n2\nleet\ncode',
        output: 'yes',
        explanation: '"leetcode" can be segmented as "leet code".',
      },
    ],
    testCases: [
      { visibility: 'public' as const, input: 'leetcode\n2\nleet\ncode', expectedOutput: 'yes', weight: 1 },
      { visibility: 'public' as const, input: 'applepen\n2\napple\npen', expectedOutput: 'yes', weight: 1 },
      { visibility: 'hidden' as const, input: 'catsandog\n2\ncats\ndog', expectedOutput: 'no', weight: 1 },
      { visibility: 'hidden' as const, input: 'a\n1\na', expectedOutput: 'yes', weight: 1 },
      { visibility: 'hidden' as const, input: 'ab\n1\na', expectedOutput: 'no', weight: 2 },
      { visibility: 'hidden' as const, input: 'aaaaaaa\n3\naaa\naaaa\naa', expectedOutput: 'yes', weight: 2 },
    ],
  },
]
