export const mediumQuestions = [
  {
    slug: "shortest-path-in-binary-grid",
    title: "Shortest Path in Binary Grid",
    topic: "algorithms",
    tags: ["bfs", "grid", "shortest-path"],
    difficultyId: "medium" as const,
    promptMd: "# Shortest Path in Binary Grid\n\nGiven an `n x n` binary grid where `0` represents an open cell and `1` represents a wall, find the shortest path from `(0, 0)` to `(n-1, n-1)` moving in all 8 directions. Return the number of cells in the shortest path, or `-1` if unreachable.\n\n## Input Format\n\n- First line: n (1 <= n <= 1000)\n- Next n lines: n characters, '0' or '1'\n\n## Output Format\n\nA single integer.",
    examples: [
      { input: "5\n00100\n00100\n00000\n00011\n00010", output: "10", explanation: "One shortest path has length 10." },
    ],
    testCases: [
      { visibility: "public", input: "5\n00100\n00100\n00000\n00011\n00010", expectedOutput: "10", weight: 1 },
      { visibility: "public", input: "3\n000\n110\n000", expectedOutput: "5", weight: 1 },
      { visibility: "public", input: "2\n01\n10", expectedOutput: "-1", weight: 1 },
      { visibility: "hidden", input: "1\n0", expectedOutput: "1", weight: 1 },
      { visibility: "hidden", input: "4\n0000\n1110\n0000\n0111", expectedOutput: "7", weight: 2 },
      { visibility: "hidden", input: "3\n000\n010\n000", expectedOutput: "3", weight: 2 },
      { visibility: "hidden", input: "5\n01111\n01111\n01111\n01111\n00000", expectedOutput: "9", weight: 3 },
      { visibility: "hidden", input: "6\n000000\n011110\n000010\n011110\n000000\n111110", expectedOutput: "12", weight: 3 },
    ],
  },
  {
    slug: "minimum-maximum-allocation",
    title: "Minimum Maximum Allocation",
    topic: "algorithms",
    tags: ["binary-search", "greedy"],
    difficultyId: "medium" as const,
    promptMd: "# Minimum Maximum Allocation\n\nGiven an array `arr` of `n` positive integers and `m` workers, assign contiguous subarrays to workers. Minimize the maximum load among all workers.\n\n## Input Format\n\n- First line: n and m (1 <= m <= n <= 100000)\n- Second line: n positive integers\n\n## Output Format\n\nA single integer.",
    examples: [
      { input: "5 3\n1 2 3 4 5", output: "6", explanation: "Split as [1,2,3] [4] [5]." },
    ],
    testCases: [
      { visibility: "public", input: "5 3\n1 2 3 4 5", expectedOutput: "6", weight: 1 },
      { visibility: "public", input: "4 2\n10 20 30 40", expectedOutput: "60", weight: 1 },
      { visibility: "hidden", input: "1 1\n5", expectedOutput: "5", weight: 1 },
      { visibility: "hidden", input: "3 3\n7 2 5", expectedOutput: "7", weight: 1 },
      { visibility: "hidden", input: "5 1\n1 2 3 4 5", expectedOutput: "15", weight: 2 },
      { visibility: "hidden", input: "5 5\n1 2 3 4 5", expectedOutput: "5", weight: 2 },
      { visibility: "hidden", input: "6 2\n5 1 3 7 2 8", expectedOutput: "15", weight: 3 },
      { visibility: "hidden", input: "8 3\n2 4 7 1 6 3 8 5", expectedOutput: "13", weight: 3 },
    ],
  },
  {
    slug: "task-scheduling-max-profit",
    title: "Task Scheduling for Maximum Profit",
    topic: "algorithms",
    tags: ["greedy", "heap", "scheduling"],
    difficultyId: "medium" as const,
    promptMd: "# Task Scheduling for Maximum Profit\n\nGiven `n` tasks each with a deadline and profit (1 unit of time each), find the maximum total profit achievable by scheduling at most one task per time unit before its deadline.\n\n## Input Format\n\n- First line: n (1 <= n <= 100000)\n- Next n lines: deadline and profit\n\n## Output Format\n\nA single integer.",
    examples: [
      { input: "4\n2 50\n1 20\n2 10\n3 30", output: "100", explanation: "Schedule at deadlines 1, 2, 3 for profits 20, 50, 30." },
    ],
    testCases: [
      { visibility: "public", input: "4\n2 50\n1 20\n2 10\n3 30", expectedOutput: "100", weight: 1 },
      { visibility: "public", input: "3\n1 10\n2 20\n3 30", expectedOutput: "60", weight: 1 },
      { visibility: "hidden", input: "1\n1 5", expectedOutput: "5", weight: 1 },
      { visibility: "hidden", input: "3\n1 10\n1 20\n1 30", expectedOutput: "30", weight: 1 },
      { visibility: "hidden", input: "5\n2 40\n2 30\n1 25\n3 10\n3 20", expectedOutput: "85", weight: 2 },
      { visibility: "hidden", input: "4\n1 100\n1 80\n1 60\n2 90", expectedOutput: "190", weight: 2 },
      { visibility: "hidden", input: "6\n3 50\n2 60\n3 40\n1 30\n2 20\n4 70", expectedOutput: "210", weight: 3 },
      { visibility: "hidden", input: "5\n5 20\n4 18\n3 15\n2 10\n1 5", expectedOutput: "68", weight: 3 },
    ],
  },
  {
    slug: "next-greater-element",
    title: "Next Greater Element",
    topic: "data-structures",
    tags: ["monotonic-stack", "stack"],
    difficultyId: "medium" as const,
    promptMd: "# Next Greater Element\n\nGiven an array of distinct integers, for each element find the next greater element to its right. Output -1 if none exists.\n\n## Input Format\n\n- First line: n (1 <= n <= 100000)\n- Second line: n integers\n\n## Output Format\n\nA single line of n space-separated integers.",
    examples: [
      { input: "5\n4 5 2 25 7", output: "5 25 25 -1 -1", explanation: undefined },
    ],
    testCases: [
      { visibility: "public", input: "5\n4 5 2 25 7", expectedOutput: "5 25 25 -1 -1", weight: 1 },
      { visibility: "public", input: "4\n13 7 6 12", expectedOutput: "-1 12 12 -1", weight: 1 },
      { visibility: "hidden", input: "1\n42", expectedOutput: "-1", weight: 1 },
      { visibility: "hidden", input: "3\n1 2 3", expectedOutput: "2 3 -1", weight: 1 },
      { visibility: "hidden", input: "3\n3 2 1", expectedOutput: "-1 -1 -1", weight: 2 },
      { visibility: "hidden", input: "6\n6 8 0 1 3", expectedOutput: "8 -1 1 3 -1", weight: 2 },
      { visibility: "hidden", input: "5\n5 4 3 2 1", expectedOutput: "-1 -1 -1 -1 -1", weight: 3 },
      { visibility: "hidden", input: "7\n1 3 2 4 7 5 6", expectedOutput: "3 4 4 7 7 6 -1", weight: 3 },
    ],
  },
  {
    slug: "climbing-stairs-with-cost",
    title: "Climbing Stairs with Cost",
    topic: "algorithms",
    tags: ["dynamic-programming", "1d-dp"],
    difficultyId: "medium" as const,
    promptMd: "# Climbing Stairs with Cost\n\nYou are given an array `cost` where `cost[i]` is the cost of the i-th step. Once you pay the cost, you can climb one or two steps. You can start from step 0 or step 1. Return the minimum cost to reach the top.\n\n## Input Format\n\n- First line: n (2 <= n <= 1000)\n- Second line: n positive integers\n\n## Output Format\n\nA single integer.",
    examples: [
      { input: "3\n1 100 1", output: "2", explanation: "Start at index 0 (1), skip to index 2 (1). Total = 2." },
    ],
    testCases: [
      { visibility: "public", input: "6\n10 15 20 5 10 15", expectedOutput: "30", weight: 1 },
      { visibility: "public", input: "3\n1 100 1", expectedOutput: "2", weight: 1 },
      { visibility: "hidden", input: "2\n10 20", expectedOutput: "10", weight: 1 },
      { visibility: "hidden", input: "4\n1 2 3 4", expectedOutput: "4", weight: 2 },
      { visibility: "hidden", input: "5\n5 1 1 1 100", expectedOutput: "3", weight: 2 },
      { visibility: "hidden", input: "3\n10 15 20", expectedOutput: "15", weight: 2 },
      { visibility: "hidden", input: "7\n1 100 1 1 100 1 1", expectedOutput: "4", weight: 3 },
      { visibility: "hidden", input: "4\n100 1 1 1", expectedOutput: "2", weight: 3 },
    ],
  },
  {
    slug: "top-k-frequent-elements",
    title: "Top K Frequent Elements",
    topic: "data-structures",
    tags: ["heap", "hash-map", "frequency"],
    difficultyId: "medium" as const,
    promptMd: "# Top K Frequent Elements\n\nGiven an array of integers and an integer k, return the k most frequent elements in any order.\n\n## Input Format\n\n- First line: n and k\n- Second line: n integers\n\n## Output Format\n\nA single line of k space-separated integers.",
    examples: [
      { input: "6 2\n1 1 1 2 2 3", output: "1 2", explanation: "1 appears 3 times, 2 appears 2 times." },
    ],
    testCases: [
      { visibility: "public", input: "6 2\n1 1 1 2 2 3", expectedOutput: "1 2", weight: 1 },
      { visibility: "public", input: "1 1\n1", expectedOutput: "1", weight: 1 },
      { visibility: "hidden", input: "4 2\n1 2 3 4", expectedOutput: "1 2", weight: 1 },
      { visibility: "hidden", input: "7 3\n3 1 3 2 1 3 1", expectedOutput: "3 1 2", weight: 2 },
      { visibility: "hidden", input: "5 1\n5 5 5 5 5", expectedOutput: "5", weight: 1 },
      { visibility: "hidden", input: "6 3\n-1 -1 2 2 2 3", expectedOutput: "-1 2 3", weight: 2 },
    ],
  },
  {
    slug: "longest-consecutive-sequence",
    title: "Longest Consecutive Sequence",
    topic: "data-structures",
    tags: ["hash-set", "arrays"],
    difficultyId: "medium" as const,
    promptMd: "# Longest Consecutive Sequence\n\nGiven an unsorted array, find the length of the longest consecutive elements sequence.\n\n## Input Format\n\n- First line: n (0 <= n <= 100000)\n- Second line: n integers\n\n## Output Format\n\nA single integer.",
    examples: [
      { input: "6\n100 4 200 1 3 2", output: "4", explanation: "Sequence [1,2,3,4]." },
      { input: "0", output: "0", explanation: "Empty array." },
    ],
    testCases: [
      { visibility: "public", input: "6\n100 4 200 1 3 2", expectedOutput: "4", weight: 1 },
      { visibility: "public", input: "0", expectedOutput: "0", weight: 1 },
      { visibility: "hidden", input: "1\n0", expectedOutput: "1", weight: 1 },
      { visibility: "hidden", input: "9\n0 3 7 2 5 8 4 6 1", expectedOutput: "10", weight: 2 },
      { visibility: "hidden", input: "5\n1 2 0 1 3", expectedOutput: "4", weight: 2 },
      { visibility: "hidden", input: "4\n9 1 4 7", expectedOutput: "2", weight: 3 },
    ],
  },
  {
    slug: "course-schedule",
    title: "Course Schedule",
    topic: "algorithms",
    tags: ["topological-sort", "graph", "dag"],
    difficultyId: "medium" as const,
    promptMd: "# Course Schedule\n\nThere are numCourses courses with prerequisites [a, b] meaning b must come before a. Return whether all courses can be completed.\n\n## Input Format\n\n- First line: numCourses and p\n- Next p lines: a b\n\n## Output Format\n\nPrint \"yes\" or \"no\".",
    examples: [
      { input: "2 1\n1 0", output: "yes", explanation: "Take 0, then 1." },
      { input: "2 2\n1 0\n0 1", output: "no", explanation: "Circular dependency." },
    ],
    testCases: [
      { visibility: "public", input: "2 1\n1 0", expectedOutput: "yes", weight: 1 },
      { visibility: "public", input: "2 2\n1 0\n0 1", expectedOutput: "no", weight: 1 },
      { visibility: "hidden", input: "1 0", expectedOutput: "yes", weight: 1 },
      { visibility: "hidden", input: "3 2\n1 0\n2 1", expectedOutput: "yes", weight: 1 },
      { visibility: "hidden", input: "3 3\n0 1\n1 2\n2 0", expectedOutput: "no", weight: 2 },
      { visibility: "hidden", input: "5 4\n1 0\n2 1\n3 2\n4 3", expectedOutput: "yes", weight: 2 },
      { visibility: "hidden", input: "4 4\n0 1\n1 2\n2 3\n3 0", expectedOutput: "no", weight: 3 },
    ],
  },
  {
    slug: "rotting-oranges",
    title: "Rotting Oranges",
    topic: "algorithms",
    tags: ["bfs", "grid", "simulation"],
    difficultyId: "medium" as const,
    promptMd: "# Rotting Oranges\n\n0=empty, 1=fresh, 2=rotten. Every minute rotten oranges rot adjacent fresh ones. Return minimum minutes until no fresh orange remains, or -1.\n\n## Input Format\n\n- First line: r and c\n- Next r lines: c integers (0, 1, 2)\n\n## Output Format\n\nA single integer.",
    examples: [
      { input: "3 3\n2 1 1\n1 1 0\n0 1 1", output: "4", explanation: undefined },
      { input: "1 1\n1", output: "-1", explanation: "No rotten orange." },
    ],
    testCases: [
      { visibility: "public", input: "3 3\n2 1 1\n1 1 0\n0 1 1", expectedOutput: "4", weight: 1 },
      { visibility: "public", input: "1 1\n1", expectedOutput: "-1", weight: 1 },
      { visibility: "hidden", input: "1 1\n0", expectedOutput: "0", weight: 1 },
      { visibility: "hidden", input: "1 1\n2", expectedOutput: "0", weight: 1 },
      { visibility: "hidden", input: "2 2\n2 1\n1 1", expectedOutput: "2", weight: 2 },
      { visibility: "hidden", input: "3 3\n2 1 1\n1 1 1\n1 1 1", expectedOutput: "5", weight: 2 },
      { visibility: "hidden", input: "2 3\n2 1 1\n0 1 0", expectedOutput: "2", weight: 3 },
      { visibility: "hidden", input: "3 3\n2 0 0\n0 1 0\n0 0 1", expectedOutput: "-1", weight: 3 },
    ],
  },
  {
    slug: "decode-ways",
    title: "Decode Ways",
    topic: "algorithms",
    tags: ["dynamic-programming", "strings"],
    difficultyId: "medium" as const,
    promptMd: "# Decode Ways\n\nA=1, B=2, ... Z=26. Given a string of digits, return the total number of ways to decode it.\n\n## Input Format\n\nA single line containing digits.\n\n## Output Format\n\nA single integer.",
    examples: [
      { input: "226", output: "3", explanation: "BZ(2,26), VF(22,6), BBF(2,2,6)." },
      { input: "0", output: "0", explanation: "No valid decoding." },
    ],
    testCases: [
      { visibility: "public", input: "226", expectedOutput: "3", weight: 1 },
      { visibility: "public", input: "0", expectedOutput: "0", weight: 1 },
      { visibility: "hidden", input: "1", expectedOutput: "1", weight: 1 },
      { visibility: "hidden", input: "10", expectedOutput: "1", weight: 1 },
      { visibility: "hidden", input: "27", expectedOutput: "1", weight: 2 },
      { visibility: "hidden", input: "111", expectedOutput: "3", weight: 2 },
      { visibility: "hidden", input: "1111", expectedOutput: "5", weight: 3 },
      { visibility: "hidden", input: "2611055971", expectedOutput: "4", weight: 3 },
    ],
  },
  {
    slug: "number-of-islands",
    title: "Number of Islands",
    topic: "algorithms",
    tags: ["dfs", "bfs", "grid"],
    difficultyId: "medium" as const,
    promptMd: "# Number of Islands\n\nGiven a grid of '1's (land) and '0's (water), count the number of islands (connected components of land).\n\n## Input Format\n\n- First line: r and c\n- Next r lines: c characters ('0' or '1', no spaces)\n\n## Output Format\n\nA single integer.",
    examples: [
      { input: "4 5\n11010\n11000\n00100\n00010", output: "3", explanation: undefined },
      { input: "1 1\n0", output: "0", explanation: undefined },
    ],
    testCases: [
      { visibility: "public", input: "4 5\n11010\n11000\n00100\n00010", expectedOutput: "3", weight: 1 },
      { visibility: "public", input: "1 1\n0", expectedOutput: "0", weight: 1 },
      { visibility: "hidden", input: "1 1\n1", expectedOutput: "1", weight: 1 },
      { visibility: "hidden", input: "3 3\n111\n111\n111", expectedOutput: "1", weight: 2 },
      { visibility: "hidden", input: "3 3\n101\n010\n101", expectedOutput: "5", weight: 2 },
      { visibility: "hidden", input: "4 5\n11000\n00100\n00011\n00011", expectedOutput: "3", weight: 3 },
      { visibility: "hidden", input: "2 4\n1101\n0010", expectedOutput: "3", weight: 3 },
    ],
  },
  {
    slug: "spiral-matrix",
    title: "Spiral Matrix",
    topic: "algorithms",
    tags: ["simulation", "matrix"],
    difficultyId: "medium" as const,
    promptMd: "# Spiral Matrix\n\nGiven an m x n matrix, return all elements in spiral order.\n\n## Input Format\n\n- First line: m and n\n- Next m lines: n integers\n\n## Output Format\n\nA single line of m*n space-separated integers.",
    examples: [
      { input: "3 3\n1 2 3\n4 5 6\n7 8 9", output: "1 2 3 6 9 8 7 4 5", explanation: undefined },
      { input: "2 3\n1 2 3\n4 5 6", output: "1 2 3 6 5 4", explanation: undefined },
    ],
    testCases: [
      { visibility: "public", input: "3 3\n1 2 3\n4 5 6\n7 8 9", expectedOutput: "1 2 3 6 9 8 7 4 5", weight: 1 },
      { visibility: "public", input: "2 3\n1 2 3\n4 5 6", expectedOutput: "1 2 3 6 5 4", weight: 1 },
      { visibility: "hidden", input: "1 4\n1 2 3 4", expectedOutput: "1 2 3 4", weight: 1 },
      { visibility: "hidden", input: "4 1\n1\n2\n3\n4", expectedOutput: "1 2 3 4", weight: 1 },
      { visibility: "hidden", input: "1 1\n42", expectedOutput: "42", weight: 1 },
      { visibility: "hidden", input: "3 4\n1 2 3 4\n5 6 7 8\n9 10 11 12", expectedOutput: "1 2 3 4 8 12 11 10 9 5 6 7", weight: 2 },
      { visibility: "hidden", input: "4 4\n1 2 3 4\n5 6 7 8\n9 10 11 12\n13 14 15 16", expectedOutput: "1 2 3 4 8 12 16 15 14 13 9 5 6 7 11 10", weight: 3 },
    ],
  },
  {
    slug: "merge-intervals",
    title: "Merge Intervals",
    topic: "algorithms",
    tags: ["sorting", "intervals"],
    difficultyId: "medium" as const,
    promptMd: "# Merge Intervals\n\nGiven a collection of intervals, merge all overlapping ones.\n\n## Input Format\n\n- First line: n\n- Next n lines: start end\n\n## Output Format\n\nLines of merged intervals sorted by start.",
    examples: [
      { input: "4\n1 3\n2 6\n8 10\n15 18", output: "1 6\n8 10\n15 18", explanation: undefined },
      { input: "2\n1 4\n4 5", output: "1 5", explanation: undefined },
    ],
    testCases: [
      { visibility: "public", input: "4\n1 3\n2 6\n8 10\n15 18", expectedOutput: "1 6\n8 10\n15 18", weight: 1 },
      { visibility: "public", input: "2\n1 4\n4 5", expectedOutput: "1 5", weight: 1 },
      { visibility: "hidden", input: "1\n1 1", expectedOutput: "1 1", weight: 1 },
      { visibility: "hidden", input: "3\n1 4\n0 4", expectedOutput: "0 4", weight: 2 },
      { visibility: "hidden", input: "5\n1 10\n2 3\n5 7\n8 9\n11 12", expectedOutput: "1 12", weight: 2 },
      { visibility: "hidden", input: "4\n1 2\n3 4\n5 6\n7 8", expectedOutput: "1 2\n3 4\n5 6\n7 8", weight: 3 },
    ],
  },
  {
    slug: "lru-cache",
    title: "LRU Cache",
    topic: "data-structures",
    tags: ["design", "hash-map"],
    difficultyId: "medium" as const,
    promptMd: "# LRU Cache\n\nDesign an LRU cache with get(key) and put(key, value) in O(1). Evict the least recently used key when capacity exceeded.\n\n## Input Format\n\nFirst line: capacity. Then operations: \"get key\" or \"put key value\".\n\n## Output Format\n\nFor each get, print the result.",
    examples: [
      { input: "2\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2", output: "1\n-1", explanation: "Key 2 evicted." },
    ],
    testCases: [
      { visibility: "public", input: "2\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2", expectedOutput: "1\n-1", weight: 1 },
      { visibility: "hidden", input: "1\nput 1 1\nget 1\nput 2 2\nget 2", expectedOutput: "1\n-1", weight: 1 },
      { visibility: "hidden", input: "2\nput 1 1\nget 1\nput 1 10\nget 1", expectedOutput: "1\n10", weight: 2 },
      { visibility: "hidden", input: "2\nput 1 1\nput 2 2\nget 2\nput 3 3\nget 1\nget 3", expectedOutput: "2\n-1\n3", weight: 2 },
      { visibility: "hidden", input: "3\nput 1 1\nput 2 2\nput 3 3\nget 1\nput 4 4\nget 2\nget 4", expectedOutput: "1\n-1\n4", weight: 3 },
    ],
  },
]
