/**
 * Rookie difficulty questions — basic loops, conditions, arrays, strings.
 */
export const rookieQuestions = [
  {
    slug: 'absolute-value',
    title: 'Absolute Value',
    topic: 'conditions',
    tags: ['basics', 'math'],
    difficultyId: 'rookie' as const,
    promptMd: '# Absolute Value\n\nRead an integer and print its absolute value.',
    examples: [{ input: '-7', output: '7', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '-7', expectedOutput: '7', weight: 1 },
      { visibility: 'public' as const, input: '5', expectedOutput: '5', weight: 1 },
      { visibility: 'hidden' as const, input: '0', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: '-1000000', expectedOutput: '1000000', weight: 2 },
    ],
  },
  {
    slug: 'max-of-three',
    title: 'Max Of Three',
    topic: 'conditions',
    tags: ['basics', 'conditions'],
    difficultyId: 'rookie' as const,
    promptMd: '# Max Of Three\n\nRead three integers (one per line) and print the largest.',
    examples: [{ input: '3\n7\n5', output: '7', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '3\n7\n5', expectedOutput: '7', weight: 1 },
      { visibility: 'hidden' as const, input: '10\n2\n8', expectedOutput: '10', weight: 1 },
      { visibility: 'hidden' as const, input: '1\n1\n1', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '-5\n-1\n-10', expectedOutput: '-1', weight: 2 },
    ],
  },
  {
    slug: 'print-numbers',
    title: 'Print Numbers',
    topic: 'loops',
    tags: ['basics', 'loops'],
    difficultyId: 'rookie' as const,
    promptMd: '# Print Numbers\n\nRead an integer n. Print numbers 1 to n, one per line.',
    examples: [{ input: '3', output: '1\n2\n3', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '3', expectedOutput: '1\n2\n3', weight: 1 },
      { visibility: 'hidden' as const, input: '1', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '5', expectedOutput: '1\n2\n3\n4\n5', weight: 2 },
    ],
  },
  {
    slug: 'array-total',
    title: 'Array Total',
    topic: 'lists',
    tags: ['arrays', 'basics'],
    difficultyId: 'rookie' as const,
    promptMd: '# Sum Of Array\n\nThe first line contains n. The second line contains n integers separated by spaces. Print their sum.',
    examples: [{ input: '3\n1 2 3', output: '6', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '3\n1 2 3', expectedOutput: '6', weight: 1 },
      { visibility: 'hidden' as const, input: '1\n42', expectedOutput: '42', weight: 1 },
      { visibility: 'hidden' as const, input: '5\n-1 0 1 2 3', expectedOutput: '5', weight: 2 },
      { visibility: 'hidden' as const, input: '2\n-5 5', expectedOutput: '0', weight: 1 },
    ],
  },
  {
    slug: 'count-positives',
    title: 'Count Positives',
    topic: 'loops',
    tags: ['arrays', 'basics'],
    difficultyId: 'rookie' as const,
    promptMd: '# Count Positives\n\nThe first line contains n. The second line contains n integers. Print how many are strictly positive.',
    examples: [{ input: '5\n-1 0 3 -2 7', output: '2', explanation: '3 and 7 are positive' }],
    testCases: [
      { visibility: 'public' as const, input: '5\n-1 0 3 -2 7', expectedOutput: '2', weight: 1 },
      { visibility: 'hidden' as const, input: '3\n-1 -2 -3', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: '4\n1 2 3 4', expectedOutput: '4', weight: 2 },
      { visibility: 'hidden' as const, input: '1\n0', expectedOutput: '0', weight: 1 },
    ],
  },
  {
    slug: 'is-even',
    title: 'Is Even',
    topic: 'conditions',
    tags: ['basics', 'modulo'],
    difficultyId: 'rookie' as const,
    promptMd: '# Is Even\n\nRead an integer. Print `yes` if it is even, otherwise `no`.',
    examples: [{ input: '4', output: 'yes', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '4', expectedOutput: 'yes', weight: 1 },
      { visibility: 'public' as const, input: '7', expectedOutput: 'no', weight: 1 },
      { visibility: 'hidden' as const, input: '0', expectedOutput: 'yes', weight: 1 },
      { visibility: 'hidden' as const, input: '-2', expectedOutput: 'yes', weight: 2 },
    ],
  },
  {
    slug: 'swap-two',
    title: 'Swap Two Numbers',
    topic: 'variables',
    tags: ['basics', 'variables'],
    difficultyId: 'rookie' as const,
    promptMd: '# Swap Two Numbers\n\nRead two integers (one per line). Print them in reverse order (second first, then first).',
    examples: [{ input: '3\n5', output: '5\n3', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '3\n5', expectedOutput: '5\n3', weight: 1 },
      { visibility: 'hidden' as const, input: '10\n20', expectedOutput: '20\n10', weight: 1 },
      { visibility: 'hidden' as const, input: '0\n0', expectedOutput: '0\n0', weight: 1 },
    ],
  },
  {
    slug: 'string-length',
    title: 'String Length',
    topic: 'strings',
    tags: ['strings', 'basics'],
    difficultyId: 'rookie' as const,
    promptMd: '# String Length\n\nRead one line of text and print its length (number of characters).',
    examples: [{ input: 'hello', output: '5', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: 'hello', expectedOutput: '5', weight: 1 },
      { visibility: 'hidden' as const, input: '', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: 'a', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: 'clutch arena', expectedOutput: '12', weight: 2 },
    ],
  },
  {
    slug: 'last-character',
    title: 'Last Character',
    topic: 'strings',
    tags: ['strings', 'basics'],
    difficultyId: 'rookie' as const,
    promptMd: '# Last Character\n\nRead one line of text (at least 1 character) and print its last character.',
    examples: [{ input: 'clutch', output: 'h', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: 'clutch', expectedOutput: 'h', weight: 1 },
      { visibility: 'hidden' as const, input: 'a', expectedOutput: 'a', weight: 1 },
      { visibility: 'hidden' as const, input: 'hello', expectedOutput: 'o', weight: 1 },
    ],
  },
  {
    slug: 'factorial',
    title: 'Factorial',
    topic: 'loops',
    tags: ['math', 'loops'],
    difficultyId: 'rookie' as const,
    promptMd: '# Factorial\n\nRead a non-negative integer n. Print n! (n factorial). 0! = 1.',
    examples: [{ input: '5', output: '120', explanation: '5*4*3*2*1 = 120' }],
    testCases: [
      { visibility: 'public' as const, input: '5', expectedOutput: '120', weight: 1 },
      { visibility: 'hidden' as const, input: '0', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '1', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '10', expectedOutput: '3628800', weight: 2 },
    ],
  },
  {
    slug: 'countdown',
    title: 'Countdown',
    topic: 'loops',
    tags: ['basics', 'loops'],
    difficultyId: 'rookie' as const,
    promptMd: '# Countdown\n\nRead an integer n. Print n, n-1, ..., 1, one per line.',
    examples: [{ input: '3', output: '3\n2\n1', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '3', expectedOutput: '3\n2\n1', weight: 1 },
      { visibility: 'hidden' as const, input: '1', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '5', expectedOutput: '5\n4\n3\n2\n1', weight: 2 },
    ],
  },
  {
    slug: 'power-of-two',
    title: 'Power Of Two',
    topic: 'conditions',
    tags: ['math', 'bitwise'],
    difficultyId: 'rookie' as const,
    promptMd: '# Power Of Two\n\nRead a positive integer n. Print `yes` if it is a power of 2, otherwise `no`.',
    examples: [{ input: '8', output: 'yes', explanation: '8 = 2^3' }],
    testCases: [
      { visibility: 'public' as const, input: '8', expectedOutput: 'yes', weight: 1 },
      { visibility: 'public' as const, input: '6', expectedOutput: 'no', weight: 1 },
      { visibility: 'hidden' as const, input: '1', expectedOutput: 'yes', weight: 1 },
      { visibility: 'hidden' as const, input: '1024', expectedOutput: 'yes', weight: 2 },
      { visibility: 'hidden' as const, input: '1023', expectedOutput: 'no', weight: 2 },
    ],
  },
  {
    slug: 'reverse-digits',
    title: 'Reverse Digits',
    topic: 'loops',
    tags: ['math', 'loops'],
    difficultyId: 'rookie' as const,
    promptMd: '# Reverse Digits\n\nRead an integer. Print its digits reversed (drop trailing zeros from the original).',
    examples: [{ input: '1230', output: '321', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '1230', expectedOutput: '321', weight: 1 },
      { visibility: 'hidden' as const, input: '5', expectedOutput: '5', weight: 1 },
      { visibility: 'hidden' as const, input: '100', expectedOutput: '1', weight: 2 },
      { visibility: 'hidden' as const, input: '0', expectedOutput: '0', weight: 1 },
    ],
  },
  {
    slug: 'smaller-of-two',
    title: 'Smaller Of Two',
    topic: 'conditions',
    tags: ['basics', 'conditions'],
    difficultyId: 'rookie' as const,
    promptMd: '# Smaller Of Two\n\nRead two integers (one per line). Print the smaller one.',
    examples: [{ input: '7\n3', output: '3', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '7\n3', expectedOutput: '3', weight: 1 },
      { visibility: 'hidden' as const, input: '5\n5', expectedOutput: '5', weight: 1 },
      { visibility: 'hidden' as const, input: '-1\n1', expectedOutput: '-1', weight: 1 },
    ],
  },
  {
    slug: 'repeat-string',
    title: 'Repeat String',
    topic: 'strings',
    tags: ['strings', 'loops'],
    difficultyId: 'rookie' as const,
    promptMd: '# Repeat String\n\nFirst line: a string s. Second line: an integer n. Print s repeated n times (no separator).',
    examples: [{ input: 'ha\n3', output: 'hahaha', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: 'ha\n3', expectedOutput: 'hahaha', weight: 1 },
      { visibility: 'hidden' as const, input: 'x\n1', expectedOutput: 'x', weight: 1 },
      { visibility: 'hidden' as const, input: 'ab\n0', expectedOutput: '', weight: 1 },
      { visibility: 'hidden' as const, input: 'clutch\n2', expectedOutput: 'clutchclutch', weight: 2 },
    ],
  },
]
