/**
 * Starter difficulty questions — basic loops, conditions, simple data structures.
 */
export const starterQuestions = [
  {
    slug: 'sum-range',
    title: 'Sum Range',
    topic: 'loops',
    tags: ['math', 'loops'],
    difficultyId: 'starter' as const,
    promptMd: '# Sum Range\n\nRead two integers a and b (one per line). Print the sum of all integers from a to b inclusive.',
    examples: [{ input: '1\n5', output: '15', explanation: '1+2+3+4+5 = 15' }],
    testCases: [
      { visibility: 'public' as const, input: '1\n5', expectedOutput: '15', weight: 1 },
      { visibility: 'hidden' as const, input: '3\n3', expectedOutput: '3', weight: 1 },
      { visibility: 'hidden' as const, input: '5\n1', expectedOutput: '15', weight: 2 },
      { visibility: 'hidden' as const, input: '-2\n2', expectedOutput: '0', weight: 2 },
    ],
  },
  {
    slug: 'count-digits',
    title: 'Count Digits',
    topic: 'loops',
    tags: ['math', 'loops'],
    difficultyId: 'starter' as const,
    promptMd: '# Count Digits\n\nRead a non-negative integer. Print the number of digits.',
    examples: [{ input: '12345', output: '5', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '12345', expectedOutput: '5', weight: 1 },
      { visibility: 'hidden' as const, input: '0', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '7', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '1000000', expectedOutput: '7', weight: 2 },
    ],
  },
  {
    slug: 'is-prime',
    title: 'Is Prime',
    topic: 'loops',
    tags: ['math', 'number-theory'],
    difficultyId: 'starter' as const,
    promptMd: '# Is Prime\n\nRead a positive integer n. Print `yes` if it is prime, otherwise `no`.',
    examples: [{ input: '7', output: 'yes', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '7', expectedOutput: 'yes', weight: 1 },
      { visibility: 'public' as const, input: '4', expectedOutput: 'no', weight: 1 },
      { visibility: 'hidden' as const, input: '1', expectedOutput: 'no', weight: 1 },
      { visibility: 'hidden' as const, input: '2', expectedOutput: 'yes', weight: 1 },
      { visibility: 'hidden' as const, input: '97', expectedOutput: 'yes', weight: 2 },
    ],
  },
  {
    slug: 'gcd-two-numbers',
    title: 'GCD Of Two Numbers',
    topic: 'functions',
    tags: ['math', 'number-theory'],
    difficultyId: 'starter' as const,
    promptMd: '# GCD Of Two Numbers\n\nRead two positive integers (one per line). Print their greatest common divisor.',
    examples: [{ input: '12\n8', output: '4', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '12\n8', expectedOutput: '4', weight: 1 },
      { visibility: 'hidden' as const, input: '7\n7', expectedOutput: '7', weight: 1 },
      { visibility: 'hidden' as const, input: '15\n25', expectedOutput: '5', weight: 2 },
      { visibility: 'hidden' as const, input: '1\n100', expectedOutput: '1', weight: 1 },
    ],
  },
  {
    slug: 'array-sum',
    title: 'Array Sum',
    topic: 'lists',
    tags: ['arrays', 'basics'],
    difficultyId: 'starter' as const,
    promptMd: '# Array Sum\n\nThe first line contains n. The second line contains n integers separated by spaces. Print their sum.',
    examples: [{ input: '4\n1 2 3 4', output: '10', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '4\n1 2 3 4', expectedOutput: '10', weight: 1 },
      { visibility: 'hidden' as const, input: '1\n42', expectedOutput: '42', weight: 1 },
      { visibility: 'hidden' as const, input: '3\n-1 -2 -3', expectedOutput: '-6', weight: 2 },
    ],
  },
  {
    slug: 'positive-negative-zero',
    title: 'Positive Negative Zero',
    topic: 'conditions',
    tags: ['basics', 'conditions'],
    difficultyId: 'starter' as const,
    promptMd: '# Positive Negative Zero\n\nRead an integer. Print `positive`, `negative`, or `zero`.',
    examples: [{ input: '5', output: 'positive', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '5', expectedOutput: 'positive', weight: 1 },
      { visibility: 'public' as const, input: '-3', expectedOutput: 'negative', weight: 1 },
      { visibility: 'hidden' as const, input: '0', expectedOutput: 'zero', weight: 1 },
    ],
  },
  {
    slug: 'count-words',
    title: 'Count Words',
    topic: 'strings',
    tags: ['strings', 'basics'],
    difficultyId: 'starter' as const,
    promptMd: '# Count Words\n\nRead one line of space-separated words. Print the number of words.',
    examples: [{ input: 'hello world', output: '2', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: 'hello world', expectedOutput: '2', weight: 1 },
      { visibility: 'hidden' as const, input: 'one', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: 'a b c d e', expectedOutput: '5', weight: 2 },
      { visibility: 'hidden' as const, input: '   ', expectedOutput: '0', weight: 2 },
    ],
  },
  {
    slug: 'min-of-array',
    title: 'Min Of Array',
    topic: 'lists',
    tags: ['arrays', 'basics'],
    difficultyId: 'starter' as const,
    promptMd: '# Min Of Array\n\nThe first line contains n (at least 1). The second line contains n integers. Print the minimum value.',
    examples: [{ input: '3\n5 2 8', output: '2', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '3\n5 2 8', expectedOutput: '2', weight: 1 },
      { visibility: 'hidden' as const, input: '1\n42', expectedOutput: '42', weight: 1 },
      { visibility: 'hidden' as const, input: '4\n-1 -5 0 3', expectedOutput: '-5', weight: 2 },
    ],
  },
  {
    slug: 'odd-sum',
    title: 'Odd Sum',
    topic: 'loops',
    tags: ['math', 'loops'],
    difficultyId: 'starter' as const,
    promptMd: '# Odd Sum\n\nRead an integer n. Print the sum of all odd numbers from 1 to n.',
    examples: [{ input: '5', output: '9', explanation: '1+3+5 = 9' }],
    testCases: [
      { visibility: 'public' as const, input: '5', expectedOutput: '9', weight: 1 },
      { visibility: 'hidden' as const, input: '1', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '10', expectedOutput: '25', weight: 2 },
      { visibility: 'hidden' as const, input: '0', expectedOutput: '0', weight: 1 },
    ],
  },
  {
    slug: 'uppercase-first',
    title: 'Uppercase First',
    topic: 'strings',
    tags: ['strings'],
    difficultyId: 'starter' as const,
    promptMd: '# Uppercase First\n\nRead a word. Print it with only the first character uppercase and the rest lowercase.',
    examples: [{ input: 'clutch', output: 'Clutch', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: 'clutch', expectedOutput: 'Clutch', weight: 1 },
      { visibility: 'hidden' as const, input: 'HELLO', expectedOutput: 'Hello', weight: 1 },
      { visibility: 'hidden' as const, input: 'a', expectedOutput: 'A', weight: 1 },
    ],
  },
  {
    slug: 'leap-year',
    title: 'Leap Year',
    topic: 'conditions',
    tags: ['math', 'conditions'],
    difficultyId: 'starter' as const,
    promptMd: '# Leap Year\n\nRead a year. Print `leap` if it is a leap year, otherwise `not leap`.\n\nA year is a leap year if it is divisible by 4, except years divisible by 100 but not by 400.',
    examples: [{ input: '2024', output: 'leap', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '2024', expectedOutput: 'leap', weight: 1 },
      { visibility: 'public' as const, input: '2023', expectedOutput: 'not leap', weight: 1 },
      { visibility: 'hidden' as const, input: '1900', expectedOutput: 'not leap', weight: 2 },
      { visibility: 'hidden' as const, input: '2000', expectedOutput: 'leap', weight: 2 },
    ],
  },
  {
    slug: 'max-in-matrix',
    title: 'Max In Matrix',
    topic: 'lists',
    tags: ['arrays', 'nested'],
    difficultyId: 'starter' as const,
    promptMd: '# Max In Matrix\n\nFirst line: rows r and columns c. Then r lines of c integers each. Print the maximum value.',
    examples: [{ input: '2 3\n1 5 3\n4 2 6', output: '6', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '2 3\n1 5 3\n4 2 6', expectedOutput: '6', weight: 1 },
      { visibility: 'hidden' as const, input: '1 1\n42', expectedOutput: '42', weight: 1 },
      { visibility: 'hidden' as const, input: '2 2\n-1 -2\n-3 -4', expectedOutput: '-1', weight: 2 },
    ],
  },
  {
    slug: 'binary-representation',
    title: 'Binary Representation',
    topic: 'loops',
    tags: ['math', 'bitwise'],
    difficultyId: 'starter' as const,
    promptMd: '# Binary Representation\n\nRead a non-negative integer. Print its binary representation without leading zeros.',
    examples: [{ input: '10', output: '1010', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '10', expectedOutput: '1010', weight: 1 },
      { visibility: 'hidden' as const, input: '0', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: '1', expectedOutput: '1', weight: 1 },
      { visibility: 'hidden' as const, input: '255', expectedOutput: '11111111', weight: 2 },
    ],
  },
  {
    slug: 'second-of-array',
    title: 'Second Smallest',
    topic: 'lists',
    tags: ['arrays', 'sorting'],
    difficultyId: 'starter' as const,
    promptMd: '# Second Smallest\n\nThe first line contains n (at least 2). The second line contains n distinct integers. Print the second smallest.',
    examples: [{ input: '4\n3 1 4 2', output: '2', explanation: undefined }],
    testCases: [
      { visibility: 'public' as const, input: '4\n3 1 4 2', expectedOutput: '2', weight: 1 },
      { visibility: 'hidden' as const, input: '2\n10 20', expectedOutput: '20', weight: 2 },
      { visibility: 'hidden' as const, input: '3\n-5 -1 -3', expectedOutput: '-3', weight: 2 },
    ],
  },
  {
    slug: 'sum-of-odds',
    title: 'Sum Of Odds',
    topic: 'loops',
    tags: ['math', 'loops'],
    difficultyId: 'starter' as const,
    promptMd: '# Sum Of Odds\n\nRead two integers a and b (one per line). Print the sum of all odd integers from a to b inclusive.',
    examples: [{ input: '1\n5', output: '9', explanation: '1+3+5 = 9' }],
    testCases: [
      { visibility: 'public' as const, input: '1\n5', expectedOutput: '9', weight: 1 },
      { visibility: 'hidden' as const, input: '2\n2', expectedOutput: '0', weight: 1 },
      { visibility: 'hidden' as const, input: '3\n7', expectedOutput: '15', weight: 1 },
      { visibility: 'hidden' as const, input: '-3\n3', expectedOutput: '0', weight: 2 },
    ],
  },
]
